# Exploratory Data Analysis
# Summary Function
summary(universities[,c(1,2,3,5)])
# Describe Function
psych::describe(universities[c(4,6,7,8,9,10,11)])
# Structure Dunction
str(universities)
# dimension
dim(universities)
# variable and level names
dimnames(universities)
# Standard Deviation Function
sd(universities$world_rank)
sd(universities$national_rank)
sd(universities$quality_of_education)
sd(universities$alumni_employment)
sd(universities$quality_of_faculty)
sd(universities$publications)
sd(universities$influence)
sd(universities$citations)
sd(universities$patents)
sd(universities$score)
sd(universities$year)
# Mean Function
mean(universities$national_rank)
mean(universities$quality_of_education)
mean(universities$alumni_employment)
mean(universities$quality_of_faculty)
mean(universities$publications)
mean(universities$influence)
mean(universities$citations)
mean(universities$patents)
mean(universities$score)
mean(universities$year)
# Median Function
median(universities$national_rank)
median(universities$quality_of_education)
median(universities$alumni_employment)
median(universities$quality_of_faculty)
median(universities$publications)
median(universities$influence)
median(universities$citations)
median(universities$patents)
median(universities$score)
median(universities$year)
# Inter Quartile Range Function
IQR(universities$national_rank)
IQR(universities$quality_of_education)
IQR(universities$alumni_employment)
IQR(universities$quality_of_faculty)
IQR(universities$publications)
IQR(universities$influence)
IQR(universities$citations)
IQR(universities$patents)
IQR(universities$score)
IQR(universities$year)

# Skewness Function
skewness(universities$national_rank)
skewness(universities$quality_of_education)
skewness(universities$alumni_employment)
skewness(universities$quality_of_faculty)
skewness(universities$publications)
skewness(universities$influence)
skewness(universities$citations)
skewness(universities$patents)
skewness(universities$score)
skewness(universities$year)
# Kurtosis Function
kurtosis(universities$national_rank)
kurtosis(universities$quality_of_education)
kurtosis(universities$alumni_employment)
kurtosis(universities$quality_of_faculty)
kurtosis(universities$publications)
kurtosis(universities$influence)
kurtosis(universities$citations)
kurtosis(universities$patents)
kurtosis(universities$score)
kurtosis(universities$year)
# Variance Function
var(universities$alumni_employment)
var(universities$publications)
var(universities$influence)
var(universities$citations)
var(universities$patents)
var(universities$score)
# Converting Character type to Factors 
universities$quality_of_education <- as.factor(universities$quality_of_education)
universities$quality_of_faculty <- as.factor(universities$quality_of_faculty)
universities$continent <- as.factor(universities$continent)
# Converting Numerical to Factors
universities_all_cat$continent <- as.factor(universities_all_cat$continent)
universities_all_cat$quality_of_education <- as.factor(universities_all_cat$quality_of_education)
universities_all_cat$quality_of_faculty <- as.factor(universities_all_cat$quality_of_faculty)
universities_all_cat$alumni_employment <- as.factor(universities_all_cat$continent)
universities_all_cat$publications <- as.factor(universities_all_cat$publications)
universities_all_cat$influence <- as.factor(universities_all_cat$influence)
universities_all_cat$citations <- as.factor(universities_all_cat$citations)
universities_all_cat$broad_impact <- as.factor(universities_all_cat$broad_impact)
universities_all_cat$patents <- as.factor(universities_all_cat$patents)
# Multinomial Logistic Regression Function
library(nnet)
multi_reg <- multinom( quality_of_faculty ~ publications + alumni_employment + quality_of_education + influence + citations + broad_impact + patents + score+ continent,data = universities)
multi_reg
summary(multi_reg)
# Prediction Function
library(dplyr)
library(MASS)
library(tidyverse)
library(stats)
predicted.classes <- model %>%predict(university_ranking)
#Predicting the Probability Function
library(stats)
predicted_class <- predict(model, transformed, "prob") 
head(predicted_class)
#Predicting the Class Function
library(stats)
predicted_class <- predict(model, transformed, "class") 
head(predicted_class)
# Confusion Matrix Function
confusionMatrix(predicted_class, universities$quality_of_faculty)
model
# ROC Curve Function
library(pROC)
model_ROC <- multiclass.roc(universities$quality_of_faculty~as.numeric(predicted_class), plot=TRUE)
View(model_ROC)
# Data Visualization Functions
par(mfrow=c(3,1))
plot(university_ranking$quality_of_faculty, main = "Barplot: Quality of Faculty", xlab = "Quality of Faculty",ylab = "Frequency")
plot(university_ranking$quality_of_education, main = "Barplot: Quality of Education", xlab = "Quality of Education",ylab = "Frequency")
plot(university_ranking$continent, main = "Barplot: continent", xlab = "Continents",ylab = "Frequency")
par(mfrow=c(4,2))
hist(universities$alumni_employment, main = "Histogram: Alumni_Employment", xlab = "Alumni_Employment")
hist(universities$publications, main = "Histogram: Publication", xlab = "Publication")
hist(universities$influence, main = "Histogram: Influence", xlab = "Influence")
hist(universities$citations, main = "Histogram: Citations", xlab = "Citations")
hist(universities$broad_impact, main = "Histogram: Broad_Impact", xlab = "Broad_Impact")
hist(universities$score, main = "Histogram: Score", xlab = "Score")
hist(universities$patents, main = "Histogram: Patents", xlab = "Patents")